set(SOURCES
    include/plugin/ActionEventHandler.hpp
    include/plugin/AnimationEventHandler.hpp
    include/plugin/CasterAdditions.hpp
    include/plugin/CastOnBlock.hpp
    include/plugin/CastOnHit.hpp
    include/plugin/CastOnKill.hpp
    include/plugin/CheatDeath.hpp
    include/plugin/Crit.hpp
    include/plugin/DeathEventHandler.hpp
    include/plugin/DeathLoot.hpp
    include/plugin/InputEventHandler.hpp
    include/plugin/ItemLimit.hpp
    include/plugin/EquipLoad.hpp
    include/plugin/JoshuaSawyerArmorSystem.hpp
    include/plugin/KillEventHandler.hpp
    include/plugin/MagicShield.hpp
    include/plugin/MagicWeapon.hpp
    include/plugin/MenuEventHandler.hpp
    include/plugin/PapyrusExtender.hpp
    include/plugin/ParryBash.hpp
    include/plugin/PetrifiedBlood.hpp
    include/plugin/PotionsDrinkLimit.hpp
    include/plugin/ProjectileBlock.hpp
    include/plugin/ResistTweaks.hpp
    include/plugin/ResourceManager.hpp
    include/plugin/SoulLink.hpp
    include/plugin/SpeedCasting.hpp
    include/plugin/SpeedMultCap.hpp
    include/plugin/StaminaShield.hpp
    include/plugin/TimingBlock.hpp
    include/plugin/TKDodge.hpp
    include/plugin/Vampirism.hpp
    include/plugin/PoisonRework.hpp
    include/plugin/SlowTime.hpp
    include/Config.hpp
    include/Core.hpp
    include/Hooks.hpp
    include/Nameof.hpp
    include/GigaWidgetAPI.hpp
    include/toml.hpp
    include/PrecisionAPI.hpp
    src/plugin/ActionEventHandler.cpp
    src/plugin/AnimationEventHandler.cpp
    src/plugin/CasterAdditions.cpp
    src/plugin/CastOnBlock.cpp
    src/plugin/CastOnHit.cpp
    src/plugin/CastOnKill.cpp
    src/plugin/CheatDeath.cpp
    src/plugin/Crit.cpp
    src/plugin/DeathEventHandler.cpp
    src/plugin/DeathLoot.cpp
    src/plugin/InputEventHandler.cpp
    src/plugin/ItemLimit.cpp
    src/plugin/EquipLoad.cpp
    src/plugin/JoshuaSawyerArmorSystem.cpp
    src/plugin/KillEventHandler.cpp
    src/plugin/MagicShield.cpp
    src/plugin/MagicWeapon.cpp
    src/plugin/MenuEventHandler.cpp
    src/plugin/PapyrusExtender.cpp
    src/plugin/ParryBash.cpp
    src/plugin/PetrifiedBlood.cpp
    src/plugin/PotionsDrinkLimit.cpp
    src/plugin/ProjectileBlock.cpp
    src/plugin/ResistTweaks.cpp
    src/plugin/ResourceManager.cpp
    src/plugin/SoulLink.cpp
    src/plugin/SpeedCasting.cpp
    src/plugin/SpeedMultCap.cpp
    src/plugin/StaminaShield.cpp
    src/plugin/TimingBlock.cpp
    src/plugin/TKDodge.cpp
    src/plugin/Vampirism.cpp
    src/plugin/PoisonRework.cpp
    src/plugin/SlowTime.cpp
    src/Config.cpp
    src/Core.cpp
    src/Hooks.cpp
    src/Main.cpp
)
